### ISSUE TITLE
Negative Value Data

### ISSUE THREAD

**Issue by bradybekkala** [relinc/SurePulseViewer#11]
**Mark,

I have sent the screen shots regarding the issue via REL Inc. email**.

"Dear support team,

I have a short question concerning the sure pulse software. As you can see in the third photo I have attached (Screen3) the axis lable is negativ. And I am asking myself if this make sense. Is there any possiblity to change the negative numbers in absolute numbers? I want the axis starting at 0 and continuing. As you can see in the other two screenshots, I saved the ecxel document as a tabstopp text file and also changed the coding into UTF-8. So in my opinion, the import (Screen2) looks the same like in the tutorials.

I hope you understand my problem and are willing to help me.

Best regards,

Oliver Seibel"

**Comment by markhalonen** [comment]
Is this still an issue?
