### ISSUE TITLE
Hysteresis Plotting 

### ISSUE THREAD

**Issue by bradybekkala** [relinc/SurePulseViewer#12]
Please try to solve the "line filling" issue.. The most helpful sample will be 002 try3
https://drive.google.com/drive/folders/0B1RuDLXLZkWgMnZ3eHBaV3JwVkU?usp=sharing

Cannot use zip file because it will not upload.

**Comment by markhalonen** [comment]
Here's what it looks like
![image](https://cloud.githubusercontent.com/assets/7853605/18803926/de9d9efe-81c2-11e6-807e-ab069f9a1622.png)
